# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
  disable:
    - depguard

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: victoria
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
    # Allow long functions in evaluator (it's a tree-walking interpreter)
    - path: evaluator/evaluator.go
      linters:
        - funlen
        - gocyclo
